project:
  type: website
  output-dir: _site

website:
  title: "quartify - Presentation"
  navbar:
    left:
      - href: index.qmd
        text: Fran√ßais
      - href: index_en.qmd
        text: English
